### ISSUE TITLE
Using the radar camera on live setting removes the graph from dashboard

### ISSUE THREAD

**Issue by JasperSurmont** [jdejaegh/irm-kmi-ha#1]
When I set the 'live' option on the camera of the radar, the bottom graph is not shown any more. Not sure if this is an issue with HA or this integration.

P.S. thanks for this repo, it's awesome already!

**Comment by jdejaegh** [comment]
HI @JasperSurmont

I am not sure to understand what you mean with 'live' option.  Could you share the following information so I can try to reproduce your bug:

1. What version of the integration and Home Assistant do you use?
2. Where is the 'live' option you set on the camera? What is that option supposed to to?  If you have a screenshot, that would be great
3. What are you trying to achieve when you encounter the bug? 
4. What are the steps to reproduce the buggy behavior?
5. Do you use any other custom components that may be related to this bug?

Thanks!

**Comment by JasperSurmont** [comment]
Hey, sorry for the little information:

- Version 0.1.7
- On picture entity cards, you can enable the'live' function if the camera supports streaming. The radar of KMI supports this, as you can see when you open the entity (camera.radar_[name of zone]): ![Screenshot_2024-01-07-10-23-42-73_c3a231c25ed346e59462e84656a70e50.jpg](https://github.com/jdejaegh/irm-kmi-ha/assets/28810440/16b40680-1635-4029-b77b-78a2725796cb)


- When I add this camera to my dashboard, everything seems to work when the 'auto' option is set instead of 'live':
![Screenshot_2024-01-07-10-23-50-28_c3a231c25ed346e59462e84656a70e50.jpg](https://github.com/jdejaegh/irm-kmi-ha/assets/28810440/27206fb4-3f12-4074-9b16-026f406cb392)

- However, when you enable the live function, the graph at the bottom is not visible anymore:
![Screenshot_2024-01-07-10-24-08-50_c3a231c25ed346e59462e84656a70e50.jpg](https://github.com/jdejaegh/irm-kmi-ha/assets/28810440/be81f0dc-83b0-459a-9bfc-3c00b158f11e)

**Comment by jdejaegh** [comment]
Thanks for the details!

I figured out it was a matter of options with the card you use: the aspect ratio is fixed so the image is cropped.  In the card settings, **set the aspect ratio to 640:720** (this is the size of the image).  Then it should be as expected and showing live.

If this solved the issue, please close it.

![Screenshot_20240107_212154](https://github.com/jdejaegh/irm-kmi-ha/assets/31966277/a34a6b28-e553-4fcf-851a-4301fa639c90)

![image](https://github.com/jdejaegh/irm-kmi-ha/assets/31966277/53f5df4a-c31b-4756-9839-6df6fd163dda)

**Comment by JasperSurmont** [comment]
Thanks, that helped :)
