### ISSUE TITLE
Storm warning missing

### ISSUE THREAD

**Issue by patriiiiiiiiiick** [jdejaegh/irm-kmi-ha#10]
Right now, there is a storm warning for Brussels. I can't find it anywhere. Maybe the warning sensor could be used.

**Comment by jdejaegh** [comment]
Do you have it in the original app?  On mine I see an orange wind warning for Brussels currently

**Comment by jdejaegh** [comment]
On the app I have the wind alert on Brussels which is also indicated on the warning sensor in my Home Assistant instance.  I have a zone called 'bxl' on Brussels in here is the warning sensor state.  This is consistent with the only warning shown for Brussels in the app.

Do you have something else that is not consistent?

![image](https://github.com/jdejaegh/irm-kmi-ha/assets/31966277/26d9fcba-eca4-45d2-b129-61e2be4af6ea)
![nsmail](https://github.com/jdejaegh/irm-kmi-ha/assets/31966277/5593eda3-4ee2-4ea0-9c8e-c0f445fc6a12)

**Comment by patriiiiiiiiiick** [comment]
Yes, I do find this sensor. However, its state is off. I see it was last updated on 22 February 2024 at 11:20:18.

warnings: 
- slug: wind
  id: 0
  level: 2
  friendly_name: null
  text: null
  starts_at: '2024-02-22T15:00:00+01:00'
  ends_at: '2024-02-23T01:00:00+01:00'
  is_active: false

active_warnings_friendly_names: 
device_class: safety
friendly_name: Warning H123

**Comment by patriiiiiiiiiick** [comment]
The logbook:
![image](https://github.com/jdejaegh/irm-kmi-ha/assets/5151122/612b1507-303e-4745-9819-e51e8acc12cf)

**Comment by jdejaegh** [comment]
OK, that's strange: the friendly name should appear and the is_active should be true given the values of starts_at and ends_at.

I'll try to reproduce the issue this week-end when I have a bit more time to look into that.

In the meantime, if you have settings that you think may interfere with the sensor, don't hesitate to share them.

What language is set in Settings > System > General?  English, English (GB), something else?

**Comment by patriiiiiiiiiick** [comment]
English (GB) is indeed what I have. Changing it to French and then restarting HA does make it active, indeed. I see the default weather card doesn't show it.

**Comment by jdejaegh** [comment]
I managed to reproduce the bug with a slightly different outcome: when using 'en-GB' or another language, the sensor for the warnings becomes unavailable.  Now, when the language is not one that is supported by the API, it defaults to English for the warning data.

**Comment by jdejaegh** [comment]
This should be fixed in the latest release https://github.com/jdejaegh/irm-kmi-ha/releases/tag/0.2.3.  Feel free to re-open if it does not work for you.

Thanks for reporting the bug!
