### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'custom_components/irm_kmi/resources/roboto_medium.ttf'

### ISSUE THREAD

**Issue by COTMO** [jdejaegh/irm-kmi-ha#13]
Get the debug logs: go to Settings > Devices & services > IRM KMI integration > Disable debug logging.
Download the file and attach it here.
[home-assistant_irm_kmi_2024-03-24T12-32-13.602Z.log](https://github.com/jdejaegh/irm-kmi-ha/files/14735463/home-assistant_irm_kmi_2024-03-24T12-32-13.602Z.log)

**Describe the bug**
FileNotFoundError: [Errno 2] No such file or directory: 'custom_components/irm_kmi/resources/roboto_medium.ttf'

**Version**
 - Home Assistant: [2024.3.3]
 - IRM KMI integration 0.2.3

**Comment by COTMO** [comment]
I installed via HACS.
The weird thing is the file is there. But still not working.
<img width="1184" alt="image" src="https://github.com/jdejaegh/irm-kmi-ha/assets/56978008/5270d288-c027-464d-b190-902abfa3e6cc">

**Comment by jdejaegh** [comment]
Weird, indeed.  Did you try removing and re-installing the integration?

**Comment by COTMO** [comment]
I removed it completely and then reinstalled via HACS.

**Comment by jdejaegh** [comment]
I implemented another way to load the font that does not require loading the file.  It may solve this issue but I fear that there is a more general issue with your config and that the other resources won't load either (like the map background). 
This is available in the newly release version 0.2.4 (you may have to force re-download on HACS to have the new version show immediately).

**Comment by COTMO** [comment]
Its like you feared other items won't load now.

**Comment by jdejaegh** [comment]
Not surprising actually.  It looks like the working directory is not in `config` in your case.

Did the integration ever worked before in your setup?
How do you run Home Assistant?  Docker (which image), Supervisor, other?

I am not sure that the issue is really linked to the integration itself

**Comment by jdejaegh** [comment]
I think I figured it out: when loading files, I assumed that the current working directory is the `config` directory.  In version 0.2.5, I use the Home Assistant configuration object to know where the `config` directory really is.

Version 0.2.5 should solve this issue. 

@COTMO Could you try and tell me if it works for you?

**Comment by COTMO** [comment]
@jdejaegh Now it works fine. Thanks you for fixing it :)
