### ISSUE TITLE
Missing UV index data

### ISSUE THREAD

**Issue by Fe1sar** [jdejaegh/irm-kmi-ha#20]
Since one of the most recent versions the uv-index attribute seems to be missing:
![image](https://github.com/jdejaegh/irm-kmi-ha/assets/25682589/631c5cbd-3833-473e-a98b-a7317802fa88)

I think the last IRM KMI version to have this was version 0.2.4 but I could be wrong here.
Currently I'm on version 0.2.8.
Is it possible to include this attribute again?

**Comment by jdejaegh** [comment]
Strange.  Can you check in the KMI app if you see the UV index as usual?  For both cities I have (Namur and Brussels) the UV index is not shown at the moment in my app

**Comment by Fe1sar** [comment]
Same thing here...
I thought this info was there, at least I think there was because I've got a card fetching this data from your integration.
Maybe KMI isn't displaying this at the moment because there isn't any uv danger(?)

**Comment by jdejaegh** [comment]
The integration is working for UV (at least should work) but currently their API does not send any UV data.
Even their website shows strange things for UV (it says 0 for Brussels and it's definitely not 0 given the sun today): https://www.meteo.be/en/brussels

**Comment by Fe1sar** [comment]
I've noticed as well.

![image](https://github.com/jdejaegh/irm-kmi-ha/assets/25682589/9279309e-afd9-4130-a849-1f0c977d421f)

![image](https://github.com/jdejaegh/irm-kmi-ha/assets/25682589/4cb787a5-7a38-4e1c-8171-d7f3b02dbae7)

It's definitely not 0 at the moment! 
Maybe we just wait for a couple of days to see if change anything on their end.

**Comment by jdejaegh** [comment]
If it was 0, the API would return 0.  Here it does not say anything about the UV index.

Closing the issue as it is likely related to IRM API and not the integration.

**Comment by jdejaegh** [comment]
@Fe1sar In my KMI app, the UV index is back and the integration shows it as well.

**Comment by Fe1sar** [comment]
Yep, I've noticed as well.
Thanks for the update!
