### ISSUE TITLE
Warnings should be visible before they actually start

### ISSUE THREAD

**Issue by schumi2309** [jdejaegh/irm-kmi-ha#21]
hi,
I am on the latest version, I am in Belgium, in Liège, where, for the moment, there is a yellow alert in the wind, but the alert sensor always tells me "secure"
Is there anything to change or modify or is it a bug?

![Capture d’écran 2024-04-15 à 11 33 24](https://github.com/jdejaegh/irm-kmi-ha/assets/47976917/d771b8ba-103f-4db7-a394-74b44c62ea06)

![Capture d’écran 2024-04-15 à 11 34 24](https://github.com/jdejaegh/irm-kmi-ha/assets/47976917/921790b0-0793-44ea-a746-925c2e19756f)

![Capture d’écran 2024-04-15 à 11 37 18](https://github.com/jdejaegh/irm-kmi-ha/assets/47976917/0feb2c2b-a59a-48d9-8802-cfb7e26f947d)

there is indeed alert, so why tell me “secure”??

![Capture d’écran 2024-04-15 à 11 41 24](https://github.com/jdejaegh/irm-kmi-ha/assets/47976917/b2aa2004-e073-4094-826c-830de733c236)

**Comment by schumi2309** [comment]
ok, I understand. I'll see what I can do to find a solution.
On the other hand, I often lose the radar camera and especially the rain forecast information, which is listed under the "hint" section (see photo).
![Capture d’écran 2024-04-16 à 08 33 27](https://github.com/jdejaegh/irm-kmi-ha/assets/47976917/8ecad39c-b478-42d4-8077-a391690d6eab)

and it's common during the day, at certain times, I have the information, then, 10 minutes later, nothing.
is this a server problem?

**Comment by jdejaegh** [comment]
I also noticed that the API of the IRM times out several times per day.  When this happens, the integration cannot refresh the data and Home Assistant shows the sensors as 'unavailable' until a successful refresh.  Those API timeouts may explain why you don't always get the camera hint.  

To check if this the API timing out, you can open the logs of your Home Assistant (Settings > System > Logs) and look for those messages:
```
Error fetching IRM KMI weather data: Error communicating with API: Timeout error fetching information
Error fetching IRM KMI weather data: Error communicating with API: Error fetching information
```

When this happens, all the sensors of the integration go 'unavailable' for about 7 minutes (the polling interval).

I'll check if I can improve the integration to handle the timeouts when I have some time.

**Comment by jdejaegh** [comment]
I created a separate issue to track the timeouts issue.

I keep this issue to track the main question here: the warning not being shown ahead of time but only when it is truly active.

To investigate:

- [ ] Create a sensor with the start time of the next warning

**Comment by schumi2309** [comment]
The only one I see is this:

![Capture d’écran 2024-04-16 à 19 52 48](https://github.com/jdejaegh/irm-kmi-ha/assets/47976917/b7db31a3-4ecd-4c7d-8a6e-b226add5e082)

**Comment by jdejaegh** [comment]
The changes related to the warnings have been merged into main.  I tested the feature with unit tests but I'll wait until a real warning comes to see it in action before releasing it. 
The feature basically adds a timestamp sensor which show the start time or the next warning (or None if no warning are scheduled)
