### ISSUE TITLE
unknown

### ISSUE THREAD

**Issue by schumi2309** [jdejaegh/irm-kmi-ha#34]
Good morning,
I'm coming to you because I always get this "unknown" message regarding the rain forecast. Before, it warned me of rain in (x) hours, now it no longer works. Is there anything to change or modify?
I think I've had this problem since the last update of the add-on.
thank you for any information available.
Congratulations again for your superb work.

![Capture d’écran 2024-05-28 à 08 50 37](https://github.com/jdejaegh/irm-kmi-ha/assets/47976917/326bb031-a46a-4a8c-8a87-e6f4b504471f)

![Capture d’écran 2024-05-28 à 08 51 39](https://github.com/jdejaegh/irm-kmi-ha/assets/47976917/716c4054-4827-4a42-b41c-49d1081fc01a)

    irm_pluie:
      friendly_name: Prevision pluie
      value_template: >-
        {% if states.camera.radar_maison.attributes.hint == "Pas de pluie prévue prochainement" %}
          Pas de pluie
        {% endif %}

**Comment by jdejaegh** [comment]
To temporary solve this issue, you can do the following:

Go to Settings > Devices & services > IRM KMI.  Select 'Configure' next to the service and change the language override setting to whatever value from the drop down and save.  Use the ⋮ and reload the service.

The next release will solve the issue once installed.

**Comment by jdejaegh** [comment]
The fix is part of [0.2.14](https://github.com/jdejaegh/irm-kmi-ha/releases/tag/0.2.14)

Feel free to comment here if something is not working on your side

**Comment by schumi2309** [comment]
Every all fonction. 
Very thanks. 
Good job. 👌
