### ISSUE TITLE
Detected blocking call to open inside the event loop by custom integration 'irm_kmi'

### ISSUE THREAD

**Issue by gieljnssns** [jdejaegh/irm-kmi-ha#39]
**Describe the bug**
Warning s with the new HA beta

**Checklist**
- [ ] I included debug logs or at least a screenshot of the IRM KMI official app
- [ ] If I use a custom card, I checked if the stock Lovelace weather card is working

**To Reproduce**
1. Update HA to 2024.6 beta

**Expected behavior**
No warnings
**Screenshots**

**Version**
 - Home Assistant: [e.g. 2024.6.0b]
 - IRM KMI integration [e.g. 0.2.14]

**Additional context**
```
Detected blocking call to open inside the event loop by custom integration 'irm_kmi' at custom_components/irm_kmi/rain_graph.py, line 96: self._dwg.embed_font(name="Roboto Medium", filename=font_file) (offender: /usr/local/lib/python3.12/site-packages/svgwrite/container.py, line 150: data = open(filename, 'rb').read()), please create a bug report at https://github.com/jdejaegh/irm-kmi-ha/issues
Detected blocking call to open inside the event loop by custom integration 'irm_kmi' at custom_components/irm_kmi/rain_graph.py, line 304: with open(bg_image_path, 'rb') as f: (offender: /config/custom_components/irm_kmi/rain_graph.py, line 304: with open(bg_image_path, 'rb') as f:), please create a bug report at https://github.com/jdejaegh/irm-kmi-ha/issues
```

**Comment by jdejaegh** [comment]
This has been fixed in version [0.2.15](https://github.com/jdejaegh/irm-kmi-ha/releases/tag/0.2.15)
However, some async variants of the blocking calls are only available in Home Assistant 2024.6 so Home Assistant needs to be at least 2024.6 (the beta versions work as well).
