### ISSUE TITLE
Exceptional weather - not really

### ISSUE THREAD

**Issue by patriiiiiiiiiick** [jdejaegh/irm-kmi-ha#5]
Thank you for this integration!

Right now, there weather is characterised as exceptional. True is not really the case.

Screenshot with Clock Weather Card:
![Screenshot_20240119-230717](https://github.com/jdejaegh/irm-kmi-ha/assets/5151122/249c3a37-22e4-40fd-906e-688fdca8abf0)

**Comment by jdejaegh** [comment]
Thanks for trying out the integration!

As mentioned in the README, the `exceptional` state is when one of the following weather conditions is reported by the API (freezing rain or freezing fog):
![Freezing rain](https://raw.githubusercontent.com/jdejaegh/irm-kmi-ha/main/img/21-d.png) ![Freezing fog](https://raw.githubusercontent.com/jdejaegh/irm-kmi-ha/main/img/27-d.png)

This choice was made before the introduction of the warning binary sensor #4.  The idea was to represent some kind of danger.  However, the `exceptional` state is a bit vague.

In my observations over the last weeks, whenever one of those conditions is reported, a warning is also active to give more details.  

Considering this, I'll make those conditions appear as rainy and foggy (respectively).  The warning binary sensor will signal the danger more precisely.

**Comment by jdejaegh** [comment]
This is part of the release version [0.2.0](https://github.com/jdejaegh/irm-kmi-ha/releases/tag/0.2.0)
