### ISSUE TITLE
Pollen data is broken as of June 26th, 2024

### ISSUE THREAD

**Issue by jdejaegh** [jdejaegh/irm-kmi-ha#51]
Due to a change in the API, the pollen data will be `None` for all sensors.

The SVG used by the API to send pollen data changed recently and looks like the following:
<img width="500" src="https://github.com/jdejaegh/irm-kmi-ha/assets/31966277/8b8b2034-6730-45ef-9872-59b60fc0df6d" alt="Pollen data"/>

It used to look like this
<img width="500" src="https://raw.githubusercontent.com/jdejaegh/irm-kmi-ha/cb9cc62ce078d19bcf484ab218e3a0ccef9c4e69/img/pollens.png" alt="Pollen data"/>

As the integration relies on this SVG to get the data, it won't reflect the actual pollen levels for now.  It is still needed to see how the SVG looks like when multiple pollen are active at the same time.

**Comment by Alien8ions** [comment]
Hi Jules

I don't know if this is related to the above, but I've been using your integration for over a month now, works pretty nice !
Thanks for maintaining this.

The issue I found is that in the KMI app a warning for eg. grasses is issued and it's ’green' for now (no pun intended here) 
In HA all pollen sensors show as None.
Last week mugwort was in the app as well albeit without a severity issued.

This is not crippling of course but it'd be nice if these sensors behave the same as in the app.
Hope you might want to look into this.

**Comment by jdejaegh** [comment]
I'll have a look at this

**Comment by jdejaegh** [comment]
I just looked into this and from the test cases, the integration returns the same values as the app.  Here are the two test cases I used (collected in summer, when there was pollen alerts).

<img width="500" src="https://github.com/jdejaegh/irm-kmi-ha/assets/31966277/8b8b2034-6730-45ef-9872-59b60fc0df6d" alt="Pollen data"/>

<img width="500" src="https://github.com/user-attachments/assets/fd1ccfb2-8e49-4a11-a710-a117f5b63dba" alt="Pollen data"/>

I noticed that the "active" state was not implemented and fixed that in f9af56547ac6cf89b3df30b7cb1dfa1e637718b9. 

Unfortunately, with winter coming, we will have less pollen alerts to test with.  If later on you notice the issue again, feel free to reopen it here or as a new issue.
