### ISSUE TITLE
[Errno 30] Read-only file system

### ISSUE THREAD

**Issue by jdejaegh** [jdejaegh/irm-kmi-ha#58]
I am very new in home assistant...  I installed the IRM-KMI weather application, it worked OK but afterwards I had to restart the unit on a previous configuration and I cannot connect anymore on the IRM server. 
The message is 

![{DCA97851-F792-405A-BCD9-5A4E5C508C21}](https://github.com/user-attachments/assets/83fbce47-21d4-41bb-aa2a-7fdb1cbac03f)

_Originally posted by @GillesJF in https://github.com/jdejaegh/irm-kmi-ha/issues/43#issuecomment-2510264903_

**Comment by jdejaegh** [comment]
Hello @GillesJF,

Thanks for trying the integration. I see you recently joined GitHub. Here are a few common good practices:

- When reporting a bug or a problem, please open a new issue rather than commenting on an existing, unrelated issue.  It helps to track the problems, and that's why I moved your comment here as an issue.
- Before opening an issue, check if the problem has not yet been reported. You can do so in the "Issues" tab of the repository and be sure to also have a look at the closed issues. In this case, it was reported in August: #55 

With that said, you can check the links in #55 : the problem seems similar to yours and seemed unrelated to the integration. It was more likely an issue with Home Assistant configuration.  You can try the following:

1. Remove the integration from Home Assistant
2. Restart Home Assistant
3. Install the integration again

I see [you messaged](https://forum.hacf.fr/t/integration-meteo-irm-belgique-meteo-be/34713/104) the French forum with your config.  I'll try to reproduce the issue on my side in the coming days and let you know.

Feel free to reply here if you have more information or managed to solve the issue

**Comment by GillesJF** [comment]
Good morning, jdejaegh
I write this mail in French as I believe you understand and it is easier
for me. If you prefer it in English, please inform

Après avoir lu votre mail, j’ai désinstallé l’intégration météo IRM. Pour
le faire, j’ai cliqué sur la poubelle qui est derrière les trois points de
l’image que j’avais transmise.
Après avoir désinstallé, j’ai relancé home assistant.
Avant de réinstaller l’intégration j’ai regardé la configuration dans «
studio code » et je remarque que l’entrée irm_kmi est toujours présente.
Dans la page appareils et service cette intégration a disparu mais celle
ensuite « appareils », on voit l’intégration comme

IRM KMI Belgian weather update
update.irm_kmi_belgian_weather_update ⸱ HACS ⸱ —

Et home assistant me demande de mettre cette intégration à jour.

En fait, je crains que le problème provienne de ce que j’aurais
involontairement cherché à installer l’intégration deux fois en même temps.

Est-ce que j’essaye de mettre à jour ce « update » ou bien il vaut mieux
l’effacer… et dans ce cas comment?

Merci beaucoup pour votre aide
Bien à vous
Gilles


Le jeu. 5 déc. 2024 à 18:27, Jules Dejaeghere ***@***.***> a
écrit :

**Comment by GillesJF** [comment]
Please excuse my answer in French, I didn’t know it will be published on this website. 

Good news concerning the problem, after updating the Home Assistant Core version and the operating system, I reloaded the irm integration and it works fine.

**Comment by jdejaegh** [comment]
> Please excuse my answer in French, I didn’t know it will be published on this website.  

No issue for the reply in French :)

> Good news concerning the problem, after updating the Home Assistant Core version and the operating system, I reloaded the irm integration and it works fine.

Glad you found a way to make it work!
