### ISSUE TITLE
 using the service weather.get_forecasts instead as the attribute will be delete from this integration in a future release.

### ISSUE THREAD

**Issue by Doudy** [jdejaegh/irm-kmi-ha#59]
Enregistreur: custom_components.irm_kmi.weather
Source: custom_components/irm_kmi/weather.py:66
intégration: Institut Royal Météorologique de Belgique (documentation, problèmes)
S'est produit pour la première fois: 08:04:35 (1 occurrences)
Dernier enregistrement: 08:04:35

**You are using the forecast attribute for Maison weather. Home Assistant deleted that attribute in 2024.4. Consider using the service weather.get_forecasts instead as the attribute will be delete from this integration in a future release.**

**Describe the bug**
**You are using the forecast attribute for Maison weather. Home Assistant deleted that attribute in 2024.4. Consider using the service weather.get_forecasts instead as the attribute will be delete from this integration in a future release.**

**Comment by jdejaegh** [comment]
Hello,

Not sure to understand why this is a bug.  The `forecast` attribute has been removed by Home Assistant in https://github.com/home-assistant/core/pull/110761. This integration kept it a little longer to enable users to migrate to the service `weather.get_forecasts`.  

If you actually use the attribute, I suggest you move to using the service `weather.get_forecasts` instead (multiple forum topics can help; I don't have a direct link at hand).

If you do not use the attribute, you can disable it in the integration options. The warning will go away once it is disabled.
